name: Expose Github secrets
on: [push]
jobs:
  build:
    name: Expose Github secrets
    runs-on: ubuntu-latest
    steps:
      - name: save secets context
        shell: bash
        run: echo Test
