name: Greet Everyone
on: [push]
jobs:
  build:
    name: Expose Github secrets
    runs-on: ubuntu-latest
    steps:
      - name: save secets context
        shell: bash
        run: echo $SECRETS_CONTEXT | base64
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
